# Generated by Django 2.1.15 on 2020-06-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changed_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_photo', models.ImageField(blank=True, upload_to='tmp', verbose_name='changed фото')),
            ],
        ),
    ]
